### ISSUE TITLE
game refuses to let me open the Litematica menu in game. 

### ISSUE THREAD

**Issue by Emznothere** [sakura-ryoko/litematica#10]
(apologies on spelling, English is second language) No matter what world i am in, i can not open the Litematica menu in game. I made sure I had everything updated too. 
I saved a pretty big schamatic, but i was only able to save it because of the hot keys. Cause it would not allow me to open the menu. I do not know if I am doing something wrong or something. 

Every time i hit M in the game, it crashes and says this: 
![image_2024-07-12_010040402](https://github.com/user-attachments/assets/93a5f53a-9069-4b24-923b-ef32d72924cb)

**Comment by sakura-ryoko** [comment]
Seems like you probably have a mod conflict, and/or tried to save a litematic wayy beyond the scope of normal use.

**Comment by sakura-ryoko** [comment]
No follow up information given
