### ISSUE TITLE
Build doesn't work 

### ISSUE THREAD

**Issue by pepenpawn** [sakura-ryoko/litematica#103]
* What went wrong:
An exception occurred applying plugin request [id: 'fabric-loom', version: '1.8-SNAPSHOT']
> Failed to apply plugin 'fabric-loom'.
   > You are using an outdated version of Java (8). Java 17 or higher is required.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

**Comment by sakura-ryoko** [comment]
```
You are using an outdated version of Java (8). Java 17 or higher is required.
```
In fact, for 1.21+ you need Java 21.
