### ISSUE TITLE
Compatibility issues with Shaders in GUI

### ISSUE THREAD

**Issue by watertrainer** [sakura-ryoko/litematica#105]
In the current litematica version on 1.21.3, together with iris and sodium, the gui looks like this after turning on a shader (on Mac M1)
![2024-11-23_01 52 37](https://github.com/user-attachments/assets/0641613d-9028-4b87-87e3-c109d6812276). 

This is the logs
[latest.log](https://github.com/user-attachments/files/17877761/latest.log)

This is not a malilib issue, MiniHUD and Tweakeroo work without problem

**Comment by sakura-ryoko** [comment]
Does the same thing happen with other shader packs ?

**Comment by watertrainer** [comment]
Yes, i tested it with ComplementaryReimagined and Sildur's Vibrant, that were the ones which reported best compatibility for 1.21.3

**Comment by sakura-ryoko** [comment]
I have tried testing this myself and couldn't reproduce the dark Icons; BUT I did find another compatibility issue with Shaders on.  I have Pinged IMS for support in Masa's Discord.
I would recommend reporting it under the Iris Issues as well.  IMS has helped me before with Litematica compat issues.

**Comment by Ka1nnn** [comment]
Oh this has happened to me before and I was not using any shaders or anything not sure what causes it. But recently it happened when I tried to exit a world and during the exit process it all went dark lmao. All the icons and stuff. I'd test but I can't reproduce it easily as I'm not sure why it happens

**Comment by sakura-ryoko** [comment]
Under 1.21.3+, Mojang changed how the Texture Rendering works; so obviously MaLiLib had to be ported to support the newer code.  It isn't a real surprise if bugs and quirks are found; but the challenge would be to find the item(s) that causes them.

**Comment by sakura-ryoko** [comment]
The Dark Icons by the way have been reported in the Iris user support without mentioning Litematica.  It might be an Iris alone issue,
