### ISSUE TITLE
Typo in strings

### ISSUE THREAD

**Issue by Rozbiynk** [sakura-ryoko/litematica#108]
![изображение](https://github.com/user-attachments/assets/47124f45-572d-4a92-a620-eef934d622f7)
sun-regions instead of sub-regions

**Comment by Rozbiynk** [comment]
![изображение](https://github.com/user-attachments/assets/53916223-a368-419d-9279-4b6bfd5aa68e)

cuboid insteads of expand (there is no cuboid selection mode)

**Comment by sakura-ryoko** [comment]
We've chatted in Discord, and have a plan.
