### ISSUE TITLE
Easy Placement mode does not respect the new 1.21 crafter block orientation 

### ISSUE THREAD

**Issue by L-LightingX** [sakura-ryoko/litematica#11]
Easy Placement mode does not respect the new 1.21 crafter block orientation when the block is in a schematic and you place it, it will face as it normally does

**Comment by sakura-ryoko** [comment]
If you are on a server, the server Requires Servux 0.3.1 in order to properly rotate the Crafter block.  Carpet Mod will not work.

Litematica itself in Single Player, also requires Easy Place Mode Version 3 / Auto enabled.
