### ISSUE TITLE
Litematica not working on lunar client

### ISSUE THREAD

**Issue by LumpaClumpa** [sakura-ryoko/litematica#110]
I tried adding litematica with the printer addon in the 1.21.3 version on lunar client, however it won't start up. it worked perfectly fine in the 1.21 version (when i last used it) I cannot really find the a solution to the problem.

**Comment by sakura-ryoko** [comment]
Lunar for 1.21.3 is not compatible.

**Comment by LumpaClumpa** [comment]
Damn :( Thanks for the response though
