### ISSUE TITLE
Translation of Litematica into Ukrainian

### ISSUE THREAD

**Issue by StarmanMine142** [sakura-ryoko/litematica#111]
Could you add the Ukrainian translation created by me?

Download in .zip format on mediafire: https://www.mediafire.com/file/4kmvvn42evbky2r/ua_litematica.zip/file

**Comment by sakura-ryoko** [comment]
Are you able to post it not as a ZIP file?  it can be posted directly into this Issues page without using a 4th party site.

**Comment by sakura-ryoko** [comment]
I want to be sure it's not malware, I assume you understand.

**Comment by StarmanMine142** [comment]
ok i will do it now

**Comment by StarmanMine142** [comment]
[uk_ua.json](https://github.com/user-attachments/files/17992883/uk_ua.json)

**Comment by StarmanMine142** [comment]
@sakura-ryoko

Did i do everything right?

**Comment by sakura-ryoko** [comment]
For the most part, but I did add two keys since:
```json
  "litematica.gui.label.schematic_info.sponge_version": "Sponge Version: §f%d§r",
  "litematica.gui.label.schematic_info.vanilla_version": "Vanilla Structure",
```

**Comment by StarmanMine142** [comment]
@sakura-ryoko. I also translated those two keys

[uk_ua.json](https://github.com/user-attachments/files/17998870/uk_ua.json)

**Comment by sakura-ryoko** [comment]
Added into the mod

**Comment by StarmanMine142** [comment]
Hello! I noticed that you added lines related to "renderAOModernEnable", and I already translated them

[uk_ua.json](https://github.com/user-attachments/files/18051873/uk_ua.json)

**Comment by StarmanMine142** [comment]
Hello again! Сorrections and improvements

[uk_ua.json](https://github.com/user-attachments/files/18102998/uk_ua.json)
