### ISSUE TITLE
OpenGL debug message pouring out

### ISSUE THREAD

**Issue by AblazeVase69188** [sakura-ryoko/litematica#113]
[23:20:32] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'

When the blueprint of blocks is displayed in the world, the process listener keeps outputting messages above (520,000 messages for only 10 minutes. The original log is 104MB big that I think I couldn't upload it to here). The messages don't affect the fps significantly, but it can gradually fill up the disk.

When I switch the renderer from OpenGL to the "soft renderer" (maybe it's Mesa3D? I'm not sure), there will be no debug messages. It might be a compatibility issue that is hard to fix, but I hope not to look at the matica using soft renderer under the poor fps of around 10. Maybe I should find a way to disable the debug message output.

Below is some info of my device:
CPU: 12th Gen Intel(R) Core(TM) i5-12450H
GPU: Intel(R) UHD Graphics
Driver version of GPU: 31.0.101.4502
OpenGL Version: 3.2.0

**Comment by sakura-ryoko** [comment]
In my experience these OpenGL errors are caused by broken Drivers / OpenGL; and only so much that Litematica can deal with.
In some cases something like Sodium has work-a rounds for such situations.

**Comment by AblazeVase69188** [comment]
OK. I will try looking for the newest versions of Drivers. Thank you.

**Comment by AblazeVase69188** [comment]
This bug cannot be reproduced in 1.21.7. Maybe it's because of the fix of MC-293754.

**Comment by sakura-ryoko** [comment]
Under 1.21.5+ I have force-disabled the Schematic Overlay Resorting features.  This was also the cause of some errors with various graphics situations & crashes.
