### ISSUE TITLE
Litematica crashing when opening the material list.

### ISSUE THREAD

**Issue by Jonas7823** [sakura-ryoko/litematica#118]
Hi, i am using the Newest Version of Litematica and Malilib for 1.21.3.
When trying to open the Material list it saves the game and then crashes.

This is what is shown in the Launcher:
The game crashed whilst rendering screen
Error: java.lang.AbstractMethodError: Receiver class red.jackf.chesttracker.impl.compat.mods.litematica.ModIcon does not define or inherit an implementation of the resolved method 'abstract void renderAt(int, int, float, boolean, boolean, net.minecraft.class_332)' of interface fi.dy.masa.malilib.gui.interfaces.IGuiIcon.

Crashlog:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-12-10 14:47:47
Description: Rendering screen

java.lang.AbstractMethodError: Receiver class red.jackf.chesttracker.impl.compat.mods.litematica.ModIcon does not define or inherit an implementation of the resolved method 'abstract void renderAt(int, int, float, boolean, boolean, net.minecraft.class_332)' of interface fi.dy.masa.malilib.gui.interfaces.IGuiIcon.
	at knot//fi.dy.masa.malilib.gui.widgets.WidgetInfoIcon.render(WidgetInfoIcon.java:24)
	at knot//fi.dy.masa.malilib.gui.GuiBase.drawWidgets(GuiBase.java:632)
	at knot//fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:181)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$86(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$zng000$fabric-screen-api-v1$onRenderScreen(class_757.java:1912)
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//fi.dy.masa.malilib.gui.widgets.WidgetInfoIcon.render(WidgetInfoIcon.java:24)
	at knot//fi.dy.masa.malilib.gui.GuiBase.drawWidgets(GuiBase.java:632)
	at knot//fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:181)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$86(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$zng000$fabric-screen-api-v1$onRenderScreen(class_757.java:1912)

-- Screen render details --
Details:
	Screen name: fi.dy.masa.litematica.gui.GuiMaterialList
	Mouse location: Scaled: (551, 263). Absolute: (1653.000000, 789.000000)
	Screen size: Scaled: (640, 334). Absolute: (1920, 1001). Scale factor of 3.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 59.868s
	Wall uptime: 51.376s
	High-res time: 47.844s
	Client ticks: 864 ticks / 43.200s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:954)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Jonas7823'/939397, l='ClientLevel', x=121.08, y=59.00, z=-83.70]]
	Chunk stats: 729, 170
	Level dimension: minecraft:overworld
	Level spawn location: World: (1,110,14), Section: (at 1,14,14 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 144064767 game time, 149700981 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 580

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, betterstats, camerautils, chesttracker, cicada, cloth-config, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, leahs-immersive-thunder, litematica, malilib, minihud, modmenu, notes, shulkerboxtooltip, smoothscroll, sodium, tcdcommons, tweakeroo, voicechat, whereisit, xaerominimap, xaeroworldmap, xaerozoomout, yet_another_config_lib_v3, black_icons, file/Redstone+Tweaks+2.2.1.zip, file/blue-ancient-debris-e1950, file/sculk shrieker, file/Boosted Brightness.zip, file/Default-Dark-Mode-1.19.4-v1.4.0.zip

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 252110456 bytes (240 MiB) / 704643072 bytes (672 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 27.20.15002.11002
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 4096.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.5613
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 27492.38
	Virtual memory used (MiB): 13892.13
	Swap memory total (MiB): 11776.00
	Swap memory used (MiB): 90.77
	Space in storage for jna.tmpdir (MiB): available: 25053.15, total: 487540.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 25053.15, total: 487540.00
	Space in storage for io.netty.native.workdir (MiB): available: 25053.15, total: 487540.00
	Space in storage for java.io.tmpdir (MiB): available: 25053.15, total: 487540.00
	Space in storage for workdir (MiB): available: 211947.92, total: 488384.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterstats: Better Statistics Screen 3.13.2+fabric-1.21.3
		camerautils: Camera Utils 1.21.3-1.0.16
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+c47b9d4340
		chesttracker: Chest Tracker 2.6.2+1.21.3
			whereisit: Where Is It 2.6.4+1.21.2
				jackfredlib: JackFredLib 0.10.3+1.21.2
					jackfredlib-base: JackFredLib: Base 1.4.1+1.21.2
					jackfredlib-colour: JackFredLib: Colour 1.1.0+1.21.2
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.21.2
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.21.2
					jackfredlib-lying: JackFredLib: Lying 0.5.5+1.21.2
					jackfredlib-toasts: JackFredLib: Toasts 1.1.1+1.21.2
		cicada: CICADA 0.9.1+1.21.2-and-above
		cloth-config: Cloth Config v16 16.0.141
			cloth-basic-math: cloth-basic-math 0.6.1
		entityculling: EntityCulling 1.7.1
		fabric-api: Fabric API 0.107.0+1.21.3
			fabric-api-base: Fabric API Base 0.4.49+d21566ae40
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.79+c47b9d4340
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+6c3b5d4940
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4340
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4340
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.3+c47b9d4340
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.23+c47b9d4340
			fabric-command-api-v1: Fabric Command API (v1) 1.2.57+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.36+c47b9d4340
			fabric-commands-v0: Fabric Commands (v0) 0.2.74+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.6+c47b9d4340
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+1ff58ec240
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4340
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+d9873d8b40
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.15+c47b9d4340
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4340
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.6+c47b9d4340
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.10+c47b9d4340
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4340
			fabric-item-api-v1: Fabric Item API (v1) 11.1.6+c47b9d4340
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.16+e7c9ab6640
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+4402f4ee40
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.25+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.13+c47b9d4340
			fabric-message-api-v1: Fabric Message API (v1) 6.0.20+c47b9d4340
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.8+c47b9d4340
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.4+89cb0a4e40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.8+c47b9d4340
			fabric-particles-v1: Fabric Particles (v1) 4.0.9+c47b9d4340
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.3+c47b9d4340
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.1+89cb0a4e40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.4+c47b9d4340
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.4+c47b9d4340
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.14+c47b9d4340
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.82+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.6+c47b9d4340
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4340
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+e82f21f740
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.33+c47b9d4340
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.99+c47b9d4340
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+c47b9d4340
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+c47b9d4340
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4340
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		iris: Iris 1.8.0-beta.6+mc1.21.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		leahs-immersive-thunder: Immersive Thunder 1.21+1.2.2
		litematica: Litematica 0.20.2-sakura.4
		malilib: MaLiLib 0.22.3-sakura.3
		minecraft: Minecraft 1.21.3
		minihud: MiniHUD 0.33.0-sakura.4
		modmenu: Mod Menu 12.0.0-beta.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		notes: Notes 1.21-2.1.1-fabric
		shulkerboxtooltip: Shulker Box Tooltip 5.2.0+1.21.3
		smoothscroll: Smooth Scroll 2.2.1
		sodium: Sodium 0.6.0-beta.4+mc1.21.3
		tcdcommons: TCD Commons API 3.12.3+fabric-1.21.3
		tweakeroo: Tweakeroo 0.22.0-sakura.3
		voicechat: Simple Voice Chat 1.21.3-2.5.25
		xaerominimap: Xaero's Minimap 24.6.2
		xaeroworldmap: Xaero's World Map 1.39.1
		xaerozoomout: XaeroZoomout 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21.2-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.16.9-1.21.3
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 556.13, NVIDIA Corporation
	Window size: 1920x1001
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 10/32 chunks
	Resource Packs: vanilla, fabric, betterstats, camerautils, chesttracker, cicada, cloth-config, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, leahs-immersive-thunder, litematica, malilib, minihud, modmenu, notes, shulkerboxtooltip, smoothscroll, sodium, tcdcommons, tweakeroo (incompatible), voicechat, whereisit, xaerominimap (incompatible), xaeroworldmap (incompatible), xaerozoomout (incompatible), yet_another_config_lib_v3 (incompatible), black_icons, file/Redstone+Tweaks+2.2.1.zip (incompatible), file/blue-ancient-debris-e1950 (incompatible), file/sculk shrieker (incompatible), file/Boosted Brightness.zip, file/Default-Dark-Mode-1.19.4-v1.4.0.zip (incompatible)
	Current Language: en_us
	Locale: de_DE
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics

**Comment by sakura-ryoko** [comment]
This appears to be a Mod Conflict problem with some mod called `red.jackf.chesttracker`

**Comment by Jonas7823** [comment]
Thank you, removing the mod solved the problem instantly
