### ISSUE TITLE
Problem with froglights (easyPlace mode)

### ISSUE THREAD

**Issue by Pawapetie** [sakura-ryoko/litematica#119]
EasyPlace doesn’t work properly with froglights. The amount of held blocks decreases, but no block is being physically placed down. It seems like litematica fails to detect the presence of froglight blocks on the client side. When face to a froglight block (that has been manually placed), it only shows information about that froglight block in the schematic, not the client’s.

**Comment by sakura-ryoko** [comment]
Try with the newest versions listed on my GitHub, I have addressed Easy Place yesterday.

**Comment by sakura-ryoko** [comment]
See https://github.com/sakura-ryoko/litematica/issues/122 -- Same problem, and will be fixed.
