### ISSUE TITLE
problem with pots

### ISSUE THREAD

**Issue by szy060510** [sakura-ryoko/litematica#120]
The pot cannot be displayed in the schematic, and the easyplace mode cannot switch the pot. However，when holding the pot, easyplace can be used to place it normally
version：litematica-fabric-1.21-0.19.54-sakura.3

**Comment by sakura-ryoko** [comment]
Ive had other people report issues with Pots; and I have not been able to reproduce the problems.  I am going to assume that it's some Mod Conflict with some other mod trying to change the Textures of the pots.

Also, Easy Place has been addressed with yesterdays update.

**Comment by szy060510** [comment]
Yes, after testing, it was found that the enhancedblockentities mod caused Litematic to not display pots properly

**Comment by szy060510** [comment]
If possible, please fix it, or I can just disable it

**Comment by sakura-ryoko** [comment]
If another mod "changes" vanilla textures / Block Models then it's not Litematica's problem to "fix" .

**Comment by szy060510** [comment]
thanks
