### ISSUE TITLE
Text rendering bag

### ISSUE THREAD

**Issue by StarmanMine142** [sakura-ryoko/litematica#121]
![image](https://github.com/user-attachments/assets/819e26d6-4422-4262-9daf-8215088ddd5b)

In the "List of materials" menu, the text of the material that is visually the last on the screen is displayed on top of the pop-up tips

(Full screenshot)

![image](https://github.com/user-attachments/assets/08cb5abd-c9b0-465a-a38b-a180c7d76736)

**Comment by sakura-ryoko** [comment]
I am aware of this & just haven't fixed it yet.  This was due to many changes with the GUI rendering from Vanilla changes from 1.21.3+

**Comment by sakura-ryoko** [comment]
I fixed this is the upcoming version drop, sakura.6 .
Note, that there are more situations when this happens which also requires a MaLiLib update; but for this I won't publish it yet.

**Comment by sakura-ryoko** [comment]
Also take note that I have more Material List related bugs to investigate soon.
