### ISSUE TITLE
Log Direction (Easy Place)

### ISSUE THREAD

**Issue by littlebeagle** [sakura-ryoko/litematica#122]
With the latest version for 1.21.3 (0.20.2) finding that logs and wood don't place in the correct orientation when using easy place unless you click on the correct side of the block.

Happening in single player and on a server with servux installed, easy place config is set to auto.

**Comment by sakura-ryoko** [comment]
Are you using sakura.6 ?

https://github.com/sakura-ryoko/litematica/releases/tag/1.21.3-0.20.2-sakura.6

**Comment by littlebeagle** [comment]
Yep

**Comment by sakura-ryoko** [comment]
I found the problem, will be fixed for sakura.8 and above.

**Comment by littlebeagle** [comment]
Awesome, just updated the mods including including servux on our server and working. Thank you, so massively appreciated the work you're doing on these mods!
