### ISSUE TITLE
Strange selection box

### ISSUE THREAD

**Issue by Crystal0404** [sakura-ryoko/litematica#124]
create a void world, you can find it at (0, 0, 0).

[latest.log](https://github.com/user-attachments/files/18140615/latest.log)

![2024-12-15_21 40 24](https://github.com/user-attachments/assets/a43e6e3c-bbae-45e6-808a-4e25f7e795d9)

**Comment by sakura-ryoko** [comment]
This is expected behavior; it's called your Selection box, which it automatically creates one for you in "Simple Mode".  Normal Mode requires you to create them manually.

**Comment by Crystal0404** [comment]
Thank you for your reply!

---- Replied Message ----
| From | Sakura ***@***.***> |
| Date | 12/17/2024 02:18 |
| To | sakura-ryoko/litematica ***@***.***> |
| Cc | Crystal_0404 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [sakura-ryoko/litematica] Strange selection box (Issue #124) |

This is expected behavior; it's called your Selection box.
