### ISSUE TITLE
with version 1.21-0.19.54-sakura.6, it cannot render and paste the entities 

### ISSUE THREAD

**Issue by 925836765** [sakura-ryoko/litematica#125]
with version 1.21.sakura.6 and malilib.sakura.4, it cannot render the entities. And I am sure that i did not set the tag 'ignore entites' as true.
this picture shows the situation,there exist some item frame on the wall orginally,and i did not ignore entities.
![QQ20241216-023151](https://github.com/user-attachments/assets/fdd880eb-b434-475d-9ef5-7c03f754a063)
when i replace the litematica-1.21.sakura.6 with the litematic-1.21.sakura.4,it renders the item frame correctly.
this picture shows the correct situation.
![QQ20241216-023003](https://github.com/user-attachments/assets/a68686f3-c296-4304-bdd0-0098bb6a6454)
To exclude the mod conflicts, I downloaded a new version with only 'litematica and malilib' and did not change any configurations. 
this picture shows the mod's environment of the game.Only install the litematica and the library it needs.
![QQ20241216-024523](https://github.com/user-attachments/assets/c3bf536c-a53d-48c1-b721-fa3369e53d4f)
Maybe i did something wrong so I caused this problem. Do I need to change some configuration in order to paste the entities? I hope I can get some help from you. 
Thank you very much.

**Comment by sakura-ryoko** [comment]
I'll look at this later.  This is why the `sakura.X` versions exist, especially when I sync code from future builds; sometimes unexpected things can happen.

It's probably a bug.

**Comment by sakura-ryoko** [comment]
See the notes for https://github.com/sakura-ryoko/litematica/releases/tag/1.21-0.19.54-sakura.7, and also requires the MaLiLib Bump.

The actual bug was in MaLiLib's new NbtUtils / NbtWrap functions that were recently updated -->
https://github.com/sakura-ryoko/malilib/releases/tag/1.21-0.21.5-sakura.5
