### ISSUE TITLE
Schematics can not be rendered with Shader enabled

### ISSUE THREAD

**Issue by lkk9898969** [sakura-ryoko/litematica#126]
Disable Shader:
![2024-12-21_03 33 42](https://github.com/user-attachments/assets/9ef30ec3-bf82-48b2-aa5f-a7e1287c1cee)
Enable Shader:
![2024-12-21_03 33 58](https://github.com/user-attachments/assets/a70c6387-42dd-4236-95bf-33b187281eb7)
Is it possible to fix that?

using mods:
fabric-api-0.111.0+1.21.4
iris-fabric-1.8.3+mc1.21.4
litematica-fabric-1.21.4-0.21.0-sakura.9
malilib-fabric-1.21.4-0.23.0-sakura.5
sodium-fabric-0.6.3+mc1.21.4
tweakeroo-fabric-1.21.4-0.23.0-sakura.7
Xaeros_Minimap_24.6.2_Fabric_1.21.4

Shader Pack: ComplementaryReimagined_r5.3

**Comment by sakura-ryoko** [comment]
Known issue.  Disable Shaders.  @IMS212 has already been notified, and waiting on him for a fix.
