### ISSUE TITLE
Editing a syncmatic on a server causes crashes

### ISSUE THREAD

**Issue by Falsus2** [sakura-ryoko/litematica#127]
On a server with syncmatica installed, trying to edit a shared litematic file to add/replace the carpet item will cause crashes. Only happens when the mod Carpet is installed client side. (Reporting here because it crashes in a litematica environment) 

Server Version: 1.21
Client Version: 1.21.1
Carpet Version: 1.4.147
Litematica Version: 0.19.53
Syncmatica Version: 0.3.13-sakura.2

Crash Reports:
[crash-2024-12-20_14.26.01-client.txt](https://github.com/user-attachments/files/18215526/crash-2024-12-20_14.26.01-client.txt) (Placing a carpet in edit mode)
[crash-2024-12-20_14.04.36-client.txt](https://github.com/user-attachments/files/18215532/crash-2024-12-20_14.04.36-client.txt) (Replace All with carpets)

**Comment by sakura-ryoko** [comment]
Duplicate Issue.  You are somehow "Forcing" syncmatica to use an Older version of Litematica that is not compatible.
0.3.13-sakura.2 requires .54-sakura.8 +

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/litematica/releases/tag/1.21-0.19.54-sakura.9
