### ISSUE TITLE
Changing dimensions with a syncmatic loaded causes it to unload

### ISSUE THREAD

**Issue by Falsus2** [sakura-ryoko/litematica#128]
I have a syncmatic loaded in the nether, after going to the overworld and returning, the syncmatic is unloaded. Trying to once again load the syncmatic via "View Syncmatics" will cause the game to crash.

Server Version: 1.21
Client Version: 1.21.1
Litematica Version: 0.19.53
Syncmatica Version (Server and Client): 1.21-0.3.13-sakura.2

Crash Log:
[crash-2024-12-20_15.08.43-client.txt](https://github.com/user-attachments/files/18215905/crash-2024-12-20_15.08.43-client.txt)

**Comment by sakura-ryoko** [comment]
-sakura.2 requires a newer version of Litematica than .53, it needs .54 .

**Comment by sakura-ryoko** [comment]
```
	"suggests": {
		"litematica": ">=0.19.54-sakura.8",
		"malilib": ">=0.21.5-sakura.5"
	},
```

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/litematica/releases/tag/1.21-0.19.54-sakura.9

**Comment by Falsus2** [comment]
Ah, I understand now thanks! I was using modrinth for all of your mods, but syncmatica wasn't included so I got that from your github without realizing they were incompatible with each other. Sorry for issue spamming something trivial lol
