### ISSUE TITLE
Lunar 1.21.4 support (?) currently crashing.

### ISSUE THREAD

**Issue by ExplodingImplosion** [sakura-ryoko/litematica#129]
Hey there! This is my first time working with malilib and litematica, so there's a chance that there's an easy fix for this that I'm overlooking. Apologies in advance if that's the case, or if I was supposed to post this issue in the maruohon repo instead.

That being said, trying to launch litematica 1.21.4-0.21.0 w/ malilib 1.21.4-0.23.0 in lunar crashes with this log:
[8608283b-1350-4a13-afc6-8985b181153e-master.log](https://github.com/user-attachments/files/18224731/8608283b-1350-4a13-afc6-8985b181153e-master.log)
Also, no worries if you're not planning on adding Lunar support! I know that they change and break things a lot. Thanks for your time!

**Comment by Croissant4life** [comment]
This happend to me too. These are my crash logs: 
        
[crash-2024-12-22_23.10.07-client - Copy.txt](https://github.com/user-attachments/files/18226283/crash-2024-12-22_23.10.07-client.-.Copy.txt)

I don't know if it is time consuming or not but any help is appreciated. Thanks for the previous help on 1.20.6 too!
The link for that convo if you want to fact check me is here: https://github.com/maruohon/litematica/issues/842

**Comment by Croissant4life** [comment]
I've had the exact same issue, any of your time would be appreciated but if this is a lot more complicated than I anticipate than thanks for at least looking in to it.
Here are my crash logs 
[crash-2024-12-22_23.10.07-client.txt](https://github.com/user-attachments/files/18230964/crash-2024-12-22_23.10.07-client.txt)
Also thanks for you help with lunar support on 1.20.6! The convo for that is here: https://github.com/maruohon/litematica/issues/842

**Comment by Croissant4life** [comment]
oops i commented twice
i thought my comment deleted or something

**Comment by sakura-ryoko** [comment]
Known problem.  Best course of action is to uninstall lunar at this time.

**Comment by Croissant4life** [comment]
Will there be an upcoming fix to this issue?

**Comment by ExplodingImplosion** [comment]
Thanks for letting me know! I'll do that.

**Comment by sakura-ryoko** [comment]
> Will there be an upcoming fix to this issue?

As far as I am aware, its not specifically a Litematica issue.  Its not like we can just "read" the Lunar source code, because they went and "modified" the Vanilla Minecraft code; and is not open source for us to know what the issue is.

This is not a thing that Mod Authors and Open Source projects like to have to deal with & complicates the trouble shooting process.

**Comment by ExplodingImplosion** [comment]
yeah id rather not pull from dev time to look into why an open source mod doesnt work with another proprietary mod with some weird checkcast thing or whatever it was. Thanks for the reply! I've used the mod a bit on Modrinth and it's worked great :)
