### ISSUE TITLE
how do i fix this 

### ISSUE THREAD

**Issue by mathewayne1** [sakura-ryoko/litematica#132]
![Screenshot 2024-12-27 010022](https://github.com/user-attachments/assets/b798aa46-6b8e-45c5-9a36-8ca8ebe7d5e3)
![Screenshot 2024-12-27 154507](https://github.com/user-attachments/assets/a1b38f54-1346-4317-8201-defaa90bdcef)

**Comment by sakura-ryoko** [comment]
Install malilib, it needs to be a JAR file just like Litematica; not a folder.

Also, you may be better off just grabbing the Modrinth releases:
--> https://modrinth.com/mod/malilib/versions
