### ISSUE TITLE
How do I fix this? 1.21.3

### ISSUE THREAD

**Issue by krish-varshney** [sakura-ryoko/litematica#133]
How do I fix this?

![image](https://github.com/user-attachments/assets/8851b25b-a727-4d46-817a-846d9d5fa3ab

**Comment by krish-varshney** [comment]
ok i figured it out you need to get this one: https://github.com/sakura-ryoko/malilib/releases/tag/1.21.3-0.22.4

**Comment by sakura-ryoko** [comment]
Yes they are all on Modrinth.
