### ISSUE TITLE
Servux based pasting ignoring disabled subregions

### ISSUE THREAD

**Issue by morgantic** [sakura-ryoko/litematica#16]
First of all, applause for the new servux based v3 protocol support for pasting schematics. Its amazing.

I just found one little thing slightly confusing, and that is that disabled subregions are still pasted on a server when using v3 protocol + servux - in single player, only the enabled subregions get pasted.

To reproduce, load any litematic with 2+ subregions, disable one, and paste on a server with servux and v3 protocoll enabled, all subregions will get pasted.

Is that intended, or could that be fixed?

**Comment by sakura-ryoko** [comment]
The merge is still a WIP

**Comment by sakura-ryoko** [comment]
Will be in the next update; but I am delaying due to other pending fixes.

**Comment by sakura-ryoko** [comment]
Fixed via https://github.com/sakura-ryoko/litematica/releases/tag/1.21-sakura.20
Also requires Servux 0.3.3 (https://github.com/sakura-ryoko/servux/releases/tag/1.21-0.3.3)
