### ISSUE TITLE
Inner sides of adjacent/touching blocks aren't rendered in layer mode

### ISSUE THREAD

**Issue by Falsus2** [sakura-ryoko/litematica#18]
With the same settings as previous litematica versions, the inner sides of touching blocks no longer render on sakura.19. I have overlayReducedInnerSides set to false.
![image](https://github.com/user-attachments/assets/526031e4-3361-4e1d-a2d5-e357d08d07ed)

**Comment by sakura-ryoko** [comment]
The Overlay Renderer / reduced Inner Sides is the recommended settings for now, but it is also a part of the code that I have been actively working on trying to fix.  Primarily I am trying to reduce it's 'LAG' that enabling reducedInnerSides seems to reduce.

**Comment by sakura-ryoko** [comment]
I found the issue, and it was primarily due to me working on debug code that I forgot to disable :)

It is unrelated to the Overlay code at all, but rather part of the standard block model rendering.

Will be fixed in sakura.20+

**Comment by sakura-ryoko** [comment]
See https://github.com/sakura-ryoko/litematica/releases/tag/1.21-sakura.20
