### ISSUE TITLE
When pressing F1 to hide the HUD, the Litematica HUD is not hidden.

### ISSUE THREAD

**Issue by Mifan-T** [sakura-ryoko/litematica#24]
![2024-07-18_03 50 19](https://github.com/user-attachments/assets/ec4795d2-6e46-4741-9772-d262b2c0ae4a)
In the image, the Litematica statusInfoHud and blockInfo are not hidden. 

This issue doesn't exist in the MC 1.20.4 version.
↓in MC 1.20.4
![2024-07-18_03 56 19](https://github.com/user-attachments/assets/c1c14ce6-43de-4b18-ab07-5605a6363a36)

**Comment by sakura-ryoko** [comment]
This is due to Vanilla changes in how the GameHud rendering code works, and the check for the `client.options.hudHidden` is now in different places.  It would need to be checked separately.

**Comment by sakura-ryoko** [comment]
this will be fixed under sakura 21

**Comment by sakura-ryoko** [comment]
See https://github.com/sakura-ryoko/litematica/releases/tag/1.21-sakura.21
