### ISSUE TITLE
Suggestion / Question 

### ISSUE THREAD

**Issue by FASTB1mc** [sakura-ryoko/litematica#26]
I am wondering if you are going to post Litematica, Tweakeroo and Minihud on Modrinth which currently has no projects by those names. It would be great if you did so because these are all very helpful and important mods for builders and Redstone farms and testing Redstone stuff. It is also a good and easy way to post mods and tell people that there are 1.21 versions of those mods.

Thanks, FASTB1mc

**Comment by sakura-ryoko** [comment]
See Masa's official statements on the situation.
