### ISSUE TITLE
about latest sakura20 easy place

### ISSUE THREAD

**Issue by mcmaidong** [sakura-ryoko/litematica#27]
轻松放置模式开启的提示为id名，并不是easy place  true  
使用轻松放置 放置方块时右手有了动作，不知是有意为之还是bug？？
![image](https://github.com/user-attachments/assets/bbe7cd42-8458-4f17-995a-adfbcf73be0d)

**Comment by sakura-ryoko** [comment]
See Sakura 22, and be advised that there exists many English and incorrect translations in the Chinese translation file yet.

https://github.com/sakura-ryoko/litematica/releases/tag/1.21-sakura.22
