### ISSUE TITLE
Windows Defender  scan Trojan:Script/Wacatac.B!ml  litematica-fabric-1.21-0.18.999-sakura.23.jar

### ISSUE THREAD

**Issue by Greatliu89** [sakura-ryoko/litematica#29]
When download releases jar  Windows Defender delete jar file

**Comment by S0FLGotTaken** [comment]
Got the same issue with tweakeroo

**Comment by sakura-ryoko** [comment]
False positives.

**Comment by S0FLGotTaken** [comment]
What causes WD to flag it as such, and why doesn't it happen with the original mods?

**Comment by sakura-ryoko** [comment]
Ask microsoft.

**Comment by S0FLGotTaken** [comment]
Fair enough
