### ISSUE TITLE
Litematica and the shaderpack are experiencing some issues.

### ISSUE THREAD

**Issue by Mifan-T** [sakura-ryoko/litematica#30]
https://github.com/user-attachments/assets/fc83139c-0e43-4004-ac1c-287ae206f803

As shown in the video, when I load a schematic, it displays two shadows: one normal and another strange shadow that moves with the player.

It happens with both Complementary and SEUS, so it might not be an issue with the shader  pack.

These are the mods I am using:
![image](https://github.com/user-attachments/assets/694dce0c-7731-429d-8cc9-d47bba681d1d)

**Comment by sakura-ryoko** [comment]
Those are not files from my Github.  Download them from my github first and try again.

Or why are they named like that ?

**Comment by sakura-ryoko** [comment]
Also, the shadow is from the Litematic Overlay, disable that and watch the shadows disappear.

Even though the Overlay Quads are 'translucent' they end up with a shadow using Shaders.

**Comment by sakura-ryoko** [comment]
Can you try something, and try enabling the `schematicOverlayEnableResorting` option and trying this again ?

**Comment by Mifan-T** [comment]
> Those are not files from my Github. Download them from my github first and try again.
> 
> Or why are they named like that ?

These are the files from GitHub, I just added a prefix to the names.

These are what the files looked like before renaming.
![image](https://github.com/user-attachments/assets/c21c35ec-359d-44a6-922c-deaba301a995)

**Comment by Mifan-T** [comment]
> Can you try something, and try enabling the `schematicOverlayEnableResorting` option and trying this again ?

![image](https://github.com/user-attachments/assets/ede0b069-6389-4835-9ff1-6b7e6b5232ba)
This isn't working, nothing happened.
![2024-07-19_18 09 42](https://github.com/user-attachments/assets/70eca001-f9af-4d94-a938-8b1dfb7b12ea)

**Comment by sakura-ryoko** [comment]
OK, well it's just that the Overlays are considered 'solid' so that the shader casts a shadow.  The BakedModel's that the Overlay Quads use are based on Solid Blocks.

**Comment by Slooshie1** [comment]
This wouldn't be so bad if the shadows behaved normally. This may be an Iris or Complementary issue but the shadows do not line up and move around when the camera moves and I'm hoping something can be done on your end. Thank you for all the work you do with porting all these mods btw! It's amazing
![image](https://github.com/user-attachments/assets/cadf4c26-fa21-4b0b-bc84-8177ae97cc6f)

**Comment by sakura-ryoko** [comment]
Tbh, the shader issues are hard to trouble shoot, because Iris's Development mode causes the IDE to crash, last time I checked.

**Comment by sakura-ryoko** [comment]
So as this issue stands, Unless someone can give me a solid answer as to how to "fix" invalid shader shadowing, this is "won't fix" / "cant fix"

**Comment by sakura-ryoko** [comment]
And yes, before you misunderstand, I have tried asking in the Iris Discord to simply be misunderstood, ignored, or have no helpful information.  Everything I was given has to do with "making Shader Packs" and that's not the issue here, and was not helpful.

**Comment by sakura-ryoko** [comment]
One of the answers was basically stated as "you can't fix that from a mod"
🫨

**Comment by sakura-ryoko** [comment]
So I apologize, it's not you; and I am aware of the issue before you've entered this.
