### ISSUE TITLE
Detected as malware by windows "defender" for some reason >:(

### ISSUE THREAD

**Issue by NotADinosaur** [sakura-ryoko/litematica#32]
![Untitled](https://github.com/user-attachments/assets/3dfc3644-c2c9-4b92-ad00-7f4e16c9f267)

**Comment by sakura-ryoko** [comment]
False positive.

**Comment by NotADinosaur** [comment]
I know, just thought I’d say it I guess? Unless you already knew that in which case sorry to bother you…
