### ISSUE TITLE
trojan ?

### ISSUE THREAD

**Issue by xXSoulReaverXx** [sakura-ryoko/litematica#34]
when i download the litematica jar file ik got a trojan messages en it got deleted right away (Trojan:Script/Wacatac.B!ml) ??

**Comment by Sdaiyan** [comment]
same for me

**Comment by LiquidM8** [comment]
Had no issues with this file.  Ran a full scan with ClamAV and no detection was found for this with the initial files or after the build was complete.  This may be specific possible to Windows AV blocking the scripts which happens quite frequently.

Command ran:
`clamscan -i -v -r litematica/* > scan.txt`

Results in text file
[results.txt](https://github.com/user-attachments/files/16310651/results.txt)

**Comment by xXSoulReaverXx** [comment]
i was thinking of that tnx for the scan

**Comment by sakura-ryoko** [comment]
False positive.
