### ISSUE TITLE
Windows Defender picking up sakura 24 as virus?

### ISSUE THREAD

**Issue by cqm3ron** [sakura-ryoko/litematica#35]
Title. It claims it is a Trojan.

**Comment by Madrel** [comment]
also happened to me, [here's what it says in windows defender upon trying to download the file](https://github.com/user-attachments/assets/87b92a8e-de57-4d48-b3b4-1e68ed301e6f)

**Comment by ClassicYtTheReal** [comment]
yeah i think after the new update on it to make it a fully .jar file it broke and im gonna try to turn of my firewall and see if it works

**Comment by sakura-ryoko** [comment]
false positive.
