### ISSUE TITLE
Saving a selection from server causing crash

### ISSUE THREAD

**Issue by Vieur** [sakura-ryoko/litematica#36]
Currently using 1.21-sakura.24 with MaliLib 1.21-sakura.8.

Procedure:
1. Join a server.
2. Make a selection.
3. Attempt to save it.

**Comment by sakura-ryoko** [comment]
Does the server have Servux ?

**Comment by sakura-ryoko** [comment]
There were bugs with this under older versions of Servux / Litematica.  Perhaps it's possible that the server owner has an old version installed ?

Otherwise I cannot reproduce this; with or without servux 0.3.4 installed.

**Comment by Vieur** [comment]
Hello, I apologize deeply for the very late reply. But no, the server doesn't have Servux installed. It is running on Purpur 1.21 and this are the only plugins installed: 22.07 16:07:17 [Server] INFO - AutoPickup, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, GSit, InvSeePlusPlus, LuckPerms
22.07 16:07:17 [Server] INFO Multiverse-Core, Otherside, SkinsRestorer, TreeAssist, Vault, Veinminer, WorldEdit

**Comment by sakura-ryoko** [comment]
Then disable the Data Syncer, and other Servux related options in your config.  You cant use Servux with anything non-Fabric.
