### ISSUE TITLE
Virus Warning when downloading - False Positive?

### ISSUE THREAD

**Issue by DRM001** [sakura-ryoko/litematica#38]
Not sure if you are aware but version litematica-fabric-1.21-0.18.999-sakura.24 is causing peoples antivirus to report that it is infected with the Wacatac.B!ml trojan.

**Comment by TopSigmaMax** [comment]
Same over here as well, I've downloaded 100s of mods in my time, some from GitHub and I've never experienced this issue.

**Comment by sakura-ryoko** [comment]
False positive
