### ISSUE TITLE
Downloading fails because windows thinks it is a virus

### ISSUE THREAD

**Issue by etc20974** [sakura-ryoko/litematica#39]
![image](https://github.com/user-attachments/assets/af93c6a6-f952-455a-a365-ef6913875813)
See the image for what happens when i try to download the file. 

Thanks

**Comment by Michiiiii2002** [comment]
same here fabric says thats a virus and won't load the mod

**Comment by 00JustAGuy00** [comment]
how to fix it or how to download litematica???

**Comment by etc20974** [comment]
I figured out how to download it. The issue is windows thinks it's a Trojan and the fabric launcher also thinks it is a malicious file. 

Malilib from this dev works perfectly.

**Comment by sakura-ryoko** [comment]
False Positive.
