### ISSUE TITLE
Mod marked as containing virus or unwated software while attemping to launch the game

### ISSUE THREAD

**Issue by Alfie51m** [sakura-ryoko/litematica#41]
![Screenshot 2024-07-21 212404](https://github.com/user-attachments/assets/613ca0a2-fbf7-4205-b16a-fbde9b4f1c83)

**Comment by Alfie51m** [comment]
![Screenshot 2024-07-21 212736](https://github.com/user-attachments/assets/c314e421-527b-4f5c-9046-c2b829d77710)

**Comment by ValeCliff** [comment]
Can confirm I have had the same issue with Windows automatically detecting the mod as a virus and quarantining it.

**Comment by BigBowlORice** [comment]
Is it actually a virus or is it a false flag?

**Comment by BigBowlORice** [comment]
its not dw

**Comment by 10pointstogryffindor** [comment]
The same thing happened to me too, first I could download the file and WIndows detected the virus, second time Chrome won't even let me download the jar.

**Comment by sakura-ryoko** [comment]
false positive
