### ISSUE TITLE
[Suggestion] Add keybindings to select corner 1 and corner 2 of the current selection

### ISSUE THREAD

**Issue by RandomGgames** [sakura-ryoko/litematica#47]
I tend to use the stick tool to select regions. Left and right click to place corner one and corner 2. It would be nice to have a keybind/ keybinds to select/cycle which corner is being edited to make selecting areas easier without using the menu.

**Comment by sakura-ryoko** [comment]
Use Middle Mouse Button when looking at the corner

**Comment by RandomGgames** [comment]
Oh, good to know. Is that currently configurable or is it hard coded?

**Comment by sakura-ryoko** [comment]
I believe it is called ` toolSelectElements `.  You can also use the Middle Button to "Select" selections and placements.
