### ISSUE TITLE
U NEED TO SEE THIS ONE!!

### ISSUE THREAD

**Issue by PMJisPro** [sakura-ryoko/litematica#48]
I M A WINDOWS 11 USER TRYING TO INSTALL IT AND WHEN I INSTALL IT AUTOMATICALLY DELETES FROM MY DOWNLOAD FOLDER AND IT SAYS IT CONTAINS VIRUS I HAVE DELETED MY ANTIVIRUS BUT IT IS NOT WORKING STILL!! PLEASE HELP SOON I M TRYING TO BUILD CREEPER FARM IN MY SMP!! -TALKING ABOUT LITEMATICA 1.21

**Comment by sakura-ryoko** [comment]
False positive
