### ISSUE TITLE
Swinging hand animations

### ISSUE THREAD

**Issue by sagunkayastha** [sakura-ryoko/litematica#50]
Hi, 

In update sakura.17 there is a fix: Swinging of your hand while using EasyPlace. Is it possible to to turn this feature off?

thanks.

**Comment by sakura-ryoko** [comment]
The feature was added by request by another player, so I added a config setting for disabling this.

https://github.com/sakura-ryoko/litematica/releases/tag/1.21-sakura.28

**Comment by sagunkayastha** [comment]
Thank you
