### ISSUE TITLE
1.21 Version won't let me change tool.

### ISSUE THREAD

**Issue by Schoktra** [sakura-ryoko/litematica#51]
I hate to use sticks cuz I hold them in my hand often. With previous versions I was able to set this to another tool in the game. However, with this latest version it won't let me change the tool PERIOD. I can't change it in game, and I went and closed the game, edited the config file, and relaunched the game and it said "eff your tool, we're going back to stick."

**Comment by Schoktra** [comment]
I finally got the change to stick, at least while in game, but I had to be in edit mode to do it.

**Comment by sakura-ryoko** [comment]
Set the tool item to a valid minecraft item, ie; `minecraft:netherite_pickaxe` to a new tool item to use.  It will always revert to stick if the setting is not a valid minecraft item; because the code needs to be validated on the Minecraft end.

**Comment by sakura-ryoko** [comment]
If the setting is blank or invalid, it will always default to stick, but `empty` or `minecraft:air` are valid, which causes any empty hotbar slots to be your tool.

**Comment by sakura-ryoko** [comment]
Another thing you can do, is Disable the tool via `M + T` .

**Comment by Schoktra** [comment]
I did, I had set it to minecraft:dirt and last i knew that's a valid item.

**Comment by sakura-ryoko** [comment]
Can't reproduce.  `minecraft:dirt` works fine.

![2024-07-26_18 40 22](https://github.com/user-attachments/assets/6696b499-ebd2-40ab-a87b-7e235678a005)
![2024-07-26_18 40 33](https://github.com/user-attachments/assets/d2d3194b-adc5-4838-8dfc-d9680ee0443b)
![2024-07-26_18 40 37](https://github.com/user-attachments/assets/575fae3b-5638-4af3-84e2-b1f483f1f12b)
![2024-07-26_18 40 52](https://github.com/user-attachments/assets/f2654cde-13ba-4107-aaf5-713602435264)

**Comment by charlsplayz** [comment]
have you got any other mods installed?

**Comment by Schoktra** [comment]
Yeah, I have tons of other mods installed, but mostly stuff for increasing game performance. and i also have almost the whole array of masa mods like tweakeroo, minihud, etc. only one that i know of his mods that i don't have is item scroller.
