### ISSUE TITLE
Investigating Windows Security Detection of JAR File as Trojan

### ISSUE THREAD

**Issue by epifeny** [sakura-ryoko/litematica#52]
Hi @sakura-ryoko ,

First, I want to thank you for all your hard work on this project. I’ve noticed a few issues have been closed with the response of "false positive," and while I understand this can be a common occurrence, I still have some concerns.

Would it be possible to investigate why Windows Security is detecting your jar file as `Trojan:Script/Wacatac.B!ml`? Identifying the root cause and finding a way to prevent this detection could help avoid similar issues being reported repeatedly in the future.

I appreciate your time and effort in addressing this matter. Thanks again for your dedication to the project!

Best regards

**Comment by sakura-ryoko** [comment]
There is nothing I can do to stop Microsoft from being dumb, as the "detection" has nothing to do with the code.
