### ISSUE TITLE
Doors are janky in edit mode.

### ISSUE THREAD

**Issue by Schoktra** [sakura-ryoko/litematica#53]
When you go to break a door to replace it with a different type in edit mode you have to break each half of the door separately, and when you go to place the new door it only places the bottom half.

**Comment by sakura-ryoko** [comment]
Ive tried in versions 1.20.4 through 1.21 and I cannot reproduce this problem.  The doors are replaced as expected.

**Comment by Schoktra** [comment]
![image](https://github.com/user-attachments/assets/c44da51b-0aae-4661-ab61-e288a448a480)
![image](https://github.com/user-attachments/assets/1f4fd6d9-52fe-4f49-ba7a-a7fe92ef8093)

**Comment by Schoktra** [comment]
First pic is of me trying to remove the door and only top have changing, bottom half i just right clicked with a different door and it just put a bottom half down and didn't replace. i did reset the schematic between the two attempts.

**Comment by Schoktra** [comment]
As an addendum, the grass is below the schematic, not part of it... maybe that makes a difference?

**Comment by sakura-ryoko** [comment]
Using the `schematicEditReplaceBlock` or `schematicEditReplaceAll` hotkey does not cause this issue.

**Comment by Schoktra** [comment]
Well in edit mode I can break blocks and replace them in the schematic like I'm working on a regular building, so it feels sorta weird to have to use a special key to replace the doors. But I guess I can get used to doing so if I have to. I've just always edited things and never had to use the keys, even with doors, unless I used replace all to replace all the blocks of one type.

**Comment by sakura-ryoko** [comment]
Yeah so I've asked Masa, and he said this is the expected behavior.  It is a one to one edit, which does not check block states when just clicking on the Schematic World.  There is another Hotkey combo that you can 'copy' the block state using `Alt+ Middle Click` I believe.  But for Doors, your best plan would be to use the other Hotkey.
