### ISSUE TITLE
cant compile the mod to jar file 

### ISSUE THREAD

**Issue by jolakonaalffa** [sakura-ryoko/litematica#59]
1 clone the folders to c
2 cd litematica
3 gradlew build 
error
> Configure project :
Fabric Loom: 1.6.12
Previous process has disowned the lock due to abrupt termination.
Found existing cache lock file (ACQUIRED_PREVIOUS_OWNER_DISOWNED), rebuilding loom cache. This may have been caused by a failed or canceled build.
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.

FAILURE: Build failed with an exception.

* What went wrong:
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66
> Unsupported class file major version 66

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s

**Comment by jolakonaalffa** [comment]
also i tried usin java 22, 21 and 20 and it was the same issue

**Comment by sakura-ryoko** [comment]
Use an IDE environment to build it.
