### ISSUE TITLE
No shortcut/keybinds editable,

### ISSUE THREAD

**Issue by GayakaYuki** [sakura-ryoko/litematica#64]
I can't find in my keybinds settings the one for Litematica, the mod i present and seems to work, for now i just forgot the hotkeys so guess i'll just go on an older version to learn it again. 
feels a bit strange, the stick is working, area selection too.

It's on Fabric 0.15.11 for 1.21
mod used :

Xaero's Minimap - 24.2.1
Cloth Config API - 15.0.128
Xaero's World Map - 1.38.8
MaLiLib - 0.20.0
WorldEdit - 7.3.5
Just Enough Items (JEI) - 19.5.2.66
Fabric API - 0.100.8
Xaero Zoomout - 2.0.0
Sodium - 0.5.11
Jade - 15.1.5
Indium - 1.0.34
Ty for your time, what an amazing mod btw !

**Comment by sakura-ryoko** [comment]
Change your 'Xaero's World Map - 1.38.8' Hotkey for the World Map of `M` so that you can access Litematica's Main Menu.
