### ISSUE TITLE
Inside block faces not rendering properly.

### ISSUE THREAD

**Issue by Lincsmash** [sakura-ryoko/litematica#65]
When using layered mode on any schematic i have this issue where if there would be a block above the one that is being rendered, that face is culled, I've tried disabling sodium and nvidium which i am also using which i was thinking might've been it.

![2024-08-01_01 18 14](https://github.com/user-attachments/assets/aac2c1e7-1768-41cb-b3ea-ce283d1dcfcb)
![2024-08-01_01 18 17](https://github.com/user-attachments/assets/05e542c0-ab66-422b-8567-f669138b09a4)

**Comment by sakura-ryoko** [comment]
There was a particular sakura version with this issue; please update your mods.
