### ISSUE TITLE
Cant use with Sodium / Indium (I think???)

### ISSUE THREAD

**Issue by KhosuDeimos** [sakura-ryoko/litematica#66]
I played around with the the mods in my list to see what would stop it from crashing

Somewhere between sodium, indium, lithium, iris and sodium extra that made it crash BUT it kept saying that there was a problem with indium

idrk whats going on pls help 
Crash report here 
[crash-2022-03-30_11.34.47-client.txt](https://github.com/user-attachments/files/16459613/crash-2022-03-30_11.34.47-client.txt)

**Comment by sakura-ryoko** [comment]
Litematica doesn't use Indium or Fabric Rendering.

Also, my Github is for the FABRIC versions of Litematica, from 1.20.6 + .
The log that you've posted is from Forge, and Minecraft 1.18.2
