### ISSUE TITLE
When I approach a large schematic in the game, it lags and renders crash.

### ISSUE THREAD

**Issue by Substance7384** [sakura-ryoko/litematica#7]
# Version
Game Version: 1.21
Litematica Version: fabric-1.21-0.18.999-sakura.17
Fabric Loader Version: 0.15.11
Fabric API Version: 0.100.6+1.21
MaLiLib Version: fabric-1.21-0.19.999-sakura.6.jar
JRE Version: OpenJDK Runtime Environment Zulu21.34+19-CA (build 21.0.3+9-LTS) 
# Description
I placed a large schematic in a server, which does not cause the game to crash under Litematica fabric-1.21-0.18.999-sakura.12 version. However, after updating Litematica to fabric-1.21-0.18.999-sakura.17, whenever I approach this schematic, the game becomes extremely laggy, then rendering crashes, leading to abnormal game exit.
![Schem](https://github.com/sakura-ryoko/litematica/assets/123358221/32884f62-8677-4326-8f0f-ef5d2963da26)
# Log File
[2024-07-11-3.log.gz](https://github.com/user-attachments/files/16172815/2024-07-11-3.log.gz)

**Comment by sakura-ryoko** [comment]
Take a look at my comments under https://github.com/sakura-ryoko/litematica/issues/6 to see if tweaking any of those settings makes a difference.
