### ISSUE TITLE
Visual Issue when you are inside the schematic.

### ISSUE THREAD

**Issue by wilebaldo** [sakura-ryoko/litematica#72]
When and activate the schematic and I go inside for some reason is show like a pink/purple block in the head of the player and is very very intrusive to work in the schematic with that problem.

I was before in the 1.20.4 and everything was working ok, I just upgrade the same world and the mod and now is this issue.

![Screenshot 2024-08-05 at 23 11 54](https://github.com/user-attachments/assets/ab565b9c-8a46-437a-9a75-b7c74bd03fb8)
![Screenshot 2024-08-05 at 23 12 10](https://github.com/user-attachments/assets/e60a3bd0-5e11-4486-b94b-735836e59d8f)
![Screenshot 2024-08-05 at 23 12 34](https://github.com/user-attachments/assets/4d35473c-41f8-49a0-a0c5-7909d2d79656)

**Comment by sakura-ryoko** [comment]
This is another mod causing this.  Something about fake lighting; so the "block" that it creates is not valid for the schematic.
