### ISSUE TITLE
适配valkan mod

### ISSUE THREAD

**Issue by FFDVDGD** [sakura-ryoko/litematica#73]
请问适配valkan mod的难度大吗？如果不大可以做一下适配吗，目前版本加载原理图会导致闪退。
[latest.log](https://github.com/user-attachments/files/16508587/latest.log)

**Comment by sakura-ryoko** [comment]
Update litematica, as it seems you have a very old version `0.18.999-sakura.18`

**Comment by sakura-ryoko** [comment]
Also, its not Litematica's job to cater to 'Vulcan' specifically.  If it's something that is not compatible with Sodium, then it is not compatible with Litematica.

**Comment by FFDVDGD** [comment]
OK
