### ISSUE TITLE
Game Crashes when Loading Server Terrain

### ISSUE THREAD

**Issue by DasMaloon** [sakura-ryoko/litematica#76]
When Connecting to a server, the Game Gets stuck on "Loading Terrain" and chrashes.
Tested with malilib-fabric-1.21.0-0.20.2 and litematica-fabric-1.21-0.19.1

Log File:

[latest.log](https://github.com/user-attachments/files/16573800/latest.log)

**Comment by sakura-ryoko** [comment]
The errors that I am seeing has nothing to do with Litematica; and appears to be a problem with a resource pack.

Try it without using any of the offending resource packs.

**Comment by DasMaloon** [comment]
I just tested it again without any Ressource-Packs (Should have disabled them in the first Place, when sending Log Files, since I knew it also throws some Errors, sorry), but the game still chrashes, with no Ressource-Packs and other Mods, apart from Fabric-API 0.102.0+ and the above mentioned Versions of Malilib and Litematica.

Hopefully this log File is more Clear
[latest.log](https://github.com/user-attachments/files/16574269/latest.log)

**Comment by sakura-ryoko** [comment]
The log file is identical to the first one.

**Comment by DasMaloon** [comment]
Ok nevermind, I was just a bit stupid.
I basically had too many scematics loaded on the Server back in previous Versions, including an _unreasonably_ large Main-Storage, and I loading this one upon joining the Server, caused the Chrash.

Anyway, thanks for keeping theese Mods updated, and sorry for wasting your time
