### ISSUE TITLE
Redstone looses east side connection

### ISSUE THREAD

**Issue by geg2048** [sakura-ryoko/litematica#80]
Hi I have this litematica: 
[2wABt_4x_Precision_Compactor.litematic.zip](https://github.com/user-attachments/files/16625703/2wABt_4x_Precision_Compactor.litematic.zip)

but when pasting it with version 1.21-0.19.2-alpha.1
it looses the east side:
![2024-08-15_15 26 55](https://github.com/user-attachments/assets/33d0c794-ecf0-463c-a47a-619ee155c9bb)
even though in the NBT the east is clearly set:
<img width="445" alt="Screenshot 2024-08-15 153139" src="https://github.com/user-attachments/assets/94f9ebe4-1e3a-4272-9e7c-3777cf52ae26">
`{
    Name: "minecraft:redstone_wire",
    Properties: {
      power: "11",
      west: "side",
      east: "side",
      south: "none",
      north: "up"
    }
  }`

**Comment by sakura-ryoko** [comment]
You should check the litematic file's BlockStatePalette.

**Comment by sakura-ryoko** [comment]
See the fix noted in here -> https://github.com/sakura-ryoko/litematica/releases/tag/1.21-0.19.2
