### ISSUE TITLE
[1.21] Extremely laggy ??

### ISSUE THREAD

**Issue by meowisme** [sakura-ryoko/litematica#81]
Just updated to 0.19.2 to see if that would help but when I load a schematic, the hologram lags my game significantly... I go from 100+ fps down to 18.
Anyone else dealing with this or is it just a me thing...

**Comment by sakura-ryoko** [comment]
This always happens with very large schematics, and if you have multiple of them loaded.

Try enabling `overlayReducedInnerSides` to improve your FPS with very large schematics.
