### ISSUE TITLE
当轻松放置最近块(easyPlaceFirst)为 false 时，可以在渲染投影(enableSchematicRandering) 为 false 时进行easyplace

### ISSUE THREAD

**Issue by Alphai04** [sakura-ryoko/litematica#84]
我不清楚这是不是一个bug，但老实说这个有趣的bug可以在简单放置例如浮冰时更轻松。可以给轻松放置最近块开启时也这样吗？或者单独作为一个选项“不渲染投影时仍可以简单放置”

**Comment by Alphai04** [comment]
我只在litematica-fabric-1.21-0.18.999-sakura.20版本中测试过，不清楚其他版本的情况。

**Comment by sakura-ryoko** [comment]
Update your mod, there were several fixes for Easy Place since `sakura.20`
