### ISSUE TITLE
Feature Request: Include crafter's locked slots state in schematic

### ISSUE THREAD

**Issue by Bergie31** [sakura-ryoko/litematica#87]
Crafters in many schematics require either a precise number and shape of locked slots for the recipe they're intended to craft, or else simply a number of locked slots to set their output power state. Having an output for them like `power: [0-9]` would be excellent, as well as having an inventory output similar looking to a dropper with some way to denote which slots are locked in the schematic.

**Comment by sakura-ryoko** [comment]
Crafter's Slots and items contained in the Crafter is Block Entity Data.  This should be listed in the Litematic if saved from Single Player.  For a server, you would need Servux 0.3.7 installed or another server-side mod installed in order to save the disabled_slots Block Entity Data from a Crafter.

**Comment by dpslwk** [comment]
Nice to know the data is there but would it be possible to render the `disabled` slots in the block info overlay 

Two examples here

1) Crafter setup for Barrels, we see that its full of items but not that the centre slot is disabled.
Not all crafter setup require the crafter to be per-filled like this, so some might just have the required slots locked and no items
![2024-09-08_19 52 51](https://github.com/user-attachments/assets/1d0f9ea6-6efe-4936-bf81-e585ba0bef22)
![2024-09-08_19 52 57](https://github.com/user-attachments/assets/3cdb9188-9964-40e5-ac09-fed4111129ee)


2) Crafter setup to use for comparator level 8, by slot locking
![2024-09-08_19 53 04](https://github.com/user-attachments/assets/f0f7f85b-7095-41c6-97d4-70d117b183d2)
![2024-09-08_19 54 00](https://github.com/user-attachments/assets/efd2891c-93a7-4302-9d29-dcea496125a7)

**Comment by sakura-ryoko** [comment]
The Info Overlay (Or Inventory Preview) Box was only ever designed to display Items and not anything else.

**Comment by dpslwk** [comment]
Yeah I understand that since its from way before the crafter was added but could it be updated to also show the disabled slots?

Is there an easy way to display the disabled slots in game? Even if just in some text way
