### ISSUE TITLE
Turtle helmet effect covering block description

### ISSUE THREAD

**Issue by Papaya314** [sakura-ryoko/litematica#88]
With most effects, the text automatically moves down, so it can be read, but if the only effect active is water breathing from the turtle helmet, the text stays covered and unreadable.
![2024-09-08_19 25 22](https://github.com/user-attachments/assets/e101dcfe-f94b-4f5e-a2a9-e61c744a2ee7) ![2024-09-08_19 26 55](https://github.com/user-attachments/assets/c9a428d3-038d-4018-8865-e4dc8a70a016)

Version 0.18.999

**Comment by sakura-ryoko** [comment]
I found the issue with this and fixed in snapshot.  What is happening is that the Turtle Helmet doesn't actually apply the status effect until you are in water; so the mod; even though it shows the icon, doesn't detect it as being an active status effect to shift the text down.

**Comment by sakura-ryoko** [comment]
Installing this version of MALILIB should fix this issue:
https://github.com/sakura-ryoko/malilib/releases/tag/1.21-0.20.3-sakura.2

**Comment by Papaya314** [comment]
Great! Thank you for such a quick fix.
