### ISSUE TITLE
Added synthesizer direction auto play

### ISSUE THREAD

**Issue by mcmaidong** [sakura-ryoko/litematica#89]
During my play, the direction of the synthesizer has been confusing me. Could you please add this function

**Comment by sakura-ryoko** [comment]
`synthesizer` ???

**Comment by mcmaidong** [comment]
My English is not very good。就是1.21合成器不能通过投影的轻松放置正确放置方向，可以添加这个功能吗？例如活塞和侦测器等的方向。crafter   easyplace  right faceing

**Comment by sakura-ryoko** [comment]
Easy Place V3 is required for Crafter rotations; if you are on a server with Carpet Mod's `accurateBlockPlacement`, then it will not work.  Currently, the only Server side mod that supports Crafter rotations is Servux 0.3.x ( https://github.com/sakura-ryoko/servux )
