### ISSUE TITLE
Game crashed when I building with Litematica

### ISSUE THREAD

**Issue by KunKi0827** [sakura-ryoko/litematica#9]
Game Version: 1.21
Litematica Version: fabric-1.21-0.18.999-sakura.17
Fabric Loader Version: 0.15.11
Fabric API Version: 0.100.3+1.21
MaLiLib Version: fabric-1.21-0.19.999-sakura.6.jar
JRE Version: OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)

No any lagging or what,all of a sudden game crashed.

Here is crash report:
https://mclo.gs/XEmIpn6
https://mclo.gs/Jw5oS9n

**Comment by sakura-ryoko** [comment]
I believe one of these has been fixed, but there is still one that needs to be investigated

**Comment by sakura-ryoko** [comment]
These may have been fixed by sakura.20
https://github.com/sakura-ryoko/litematica/releases/tag/1.21-sakura.20
