### ISSUE TITLE
Feature Suggestion: UNDO/REDO

### ISSUE THREAD

**Issue by MagboneD** [sakura-ryoko/litematica#91]
First, thank you, so much for keeping this project going! This mod has become a staple of the MC community. 

You've taken this out of the kindness of your heart, so I don't want to make a feature request; more like a suggestion to think about. Also, I've never dug into masa's code, so I'm not sure if this is even feasible, but has anyone ever considred putting an UNDO/REDO queue into litematica, similar to WorldEdit? 

Litematica is vastly superior to worldedit when it comes to copy/pasting block states and entities, but I often find myself switching to worldedit for certain operations simply because it has the undo/redo function. 

Anyway, thanks again for your awesome work on this project!

**Comment by wendavid552** [comment]
It is hardly possible for litematica to do so, as litematica is only a client side mod, and the only possible way is to first save the region before each time you paste, and then paste the saved version as reverting. That could be very different from worldedit.

**Comment by zly2006** [comment]
This should not be implemented by litematica, and is impossible. You can try my [Reden mod](https://modrinth.com/mod/reden)
