### ISSUE TITLE
Trojan detection

### ISSUE THREAD

**Issue by CaptainFeatherPoof** [sakura-ryoko/litematica#95]
Virus total detects trojan
Trojan.PY.Agent.AG from virus total by only 1 vender

**Comment by CaptainFeatherPoof** [comment]
no attention to be rude or anythin i believe ye hav no harmful intention its just somethin that might kill mod 
nobody wantss to fook with a 'infected' mod eh?

**Comment by sakura-ryoko** [comment]
Invalid.
